config/routes.rb
Fediaz::Application.routes.draw do
  get "library/index"
  resources :artefacts do 
    resources :attachments
  end

  root 'library#index'

end

app/models/artefact.rb
class Artefact < ActiveRecord::Base
   has_many :attachments
   accepts_nested_attributes_for :attachments, :reject_if => proc { |attrs| attrs[:asset].blank? }
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base 
  has_attached_file :asset, 
    :styles => { :thumb => "100x100>" }, 
    :default_url => "/images/:style/missing.png"    
  validates_attachment_content_type :asset, :content_type => /\Aimage\/.*\Z/
  belongs_to :artefact
  default_scope { order('weight') } 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artefacts_controller.rb
class ArtefactsController < ApplicationController
  before_action :set_artefact, only: [:show, :edit, :update, :destroy]

  layout 'admin'
  # GET /artefacts
  # GET /artefacts.json
  def index
    @artefacts = Artefact.all
  end

  # GET /artefacts/1
  # GET /artefacts/1.json
  def show
  end

  # GET /artefacts/new
  def new
    @artefact = Artefact.new
    @artefact.attachments.build
  end

  # GET /artefacts/1/edit
  def edit
    @artefact.attachments.build
  end

  # POST /artefacts
  # POST /artefacts.json
  def create
    @artefact = Artefact.new(artefact_params)

    respond_to do |format|
      if @artefact.save
        format.html { redirect_to @artefact, notice: 'Artefact was successfully created.' }
        format.json { render action: 'show', status: :created, location: @artefact }
      else
        format.html { render action: 'new' }
        format.json { render json: @artefact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artefacts/1
  # PATCH/PUT /artefacts/1.json
  def update
    respond_to do |format|
      if @artefact.update(artefact_params)
        format.html { redirect_to @artefact, notice: 'Artefact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @artefact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artefacts/1
  # DELETE /artefacts/1.json
  def destroy
    @artefact.destroy
    respond_to do |format|
      format.html { redirect_to artefacts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artefact
      @artefact = Artefact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artefact_params
      params.require(:artefact).permit(:name, :location, :technique, :team, :published, :description, {:attachments_attributes => [:asset]} )
    end


end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :set_attachment, only: [:show, :edit, :update, :destroy]
  before_action :set_artefact

  layout 'admin'

  # GET /attachments
  # GET /attachments.json
  def index
    @attachments = Attachment.find_all_by_artefact_id(@artefact.id)
  end

  # GET /attachments/1
  # GET /attachments/1.json
  def show
  end

  # GET /attachments/new
  def new
    @attachment = Attachment.new
  end

  # GET /attachments/1/edit
  def edit
  end

  # POST /attachments
  # POST /attachments.json
  def create
    @attachment = Attachment.new(attachment_params)
    @attachment.artefact = @artefact

    respond_to do |format|
      if @attachment.save
        format.html { redirect_to [@artefact, @attachment], notice: 'Attachment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @attachment }
      else
        format.html { render action: 'new' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attachments/1
  # PATCH/PUT /attachments/1.json
  def update
    @attachment.artefact = @artefact

    respond_to do |format|
      if @attachment.update(attachment_params)
        format.html { redirect_to [@artefact, @attachment], notice: 'Attachment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attachments/1
  # DELETE /attachments/1.json
  def destroy
    @attachment.destroy
    respond_to do |format|
      format.html { redirect_to artefact_attachments_url(@artefact) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attachment
      @attachment = Attachment.find(params[:id])
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_artefact
      @artefact = Artefact.find(params[:artefact_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attachment_params
      params.require(:attachment).permit(:name, :asset, :weight, :asset_file_name, :artefact_id )
    end
end

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  layout 'public'
  def index
    @artefacts = Artefact.find_all_by_published(true)
    @artefact = Artefact.first
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artefacts_helper.rb
module ArtefactsHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/views/artefacts/_form.html.erb
<%= form_for(@artefact, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @artefact.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@artefact.errors.count, "error") %> prohibited this artefact from being saved:</h4>

      <ul>
      <% @artefact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :location, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :location, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :technique, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :technique, :class => "form-control" %>
    </div>
  </div>
   
  <div class="form-group">
    <%= f.label :team, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :team, :class => "form-control" %>
    </div>
  </div>
  
  <div class="form-group">
    <%= f.label :published, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :published, :class => "form-control" %>
    </div>
  </div>  
  
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/artefacts/edit.html.erb
<div class="page-header">
  <%= link_to artefacts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @artefact, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <%= link_to artefact_attachments_path(@artefact.id), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-paperclip"></span>
    Edit Attachments
  <% end %>
  <h1>Editing artefact</h1>
</div>

<%= render 'form' %>

app/views/artefacts/index.html.erb
<div class="page-header">
  <%= link_to new_artefact_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Artefact
  <% end %>
  <h1>Listing artefacts</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Location</th>
            <th>Technique</th>
            <th>Team</th>
            <th>Description</th>
            <th>Published</th>
            <th>Attachments</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @artefacts) do |artefact| %>
            <td><%= artefact.name %></td>
            <td><%= artefact.location %></td>
            <td><%= artefact.technique %></td>
            <td><%= artefact.team %></td>
            <td><%= artefact.description %></td>
            <td><%= artefact.published %></td>
            <td><%= link_to artefact.attachments.length, artefact_attachments_path(artefact.id)%></td>
            <td><%= link_to 'Show', artefact %></td>
        <td><%= link_to 'Edit', edit_artefact_path(artefact) %></td>
        <td><%= link_to 'Destroy', artefact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/artefacts/new.html.erb
<div class="page-header">
  <%= link_to artefacts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New artefact</h1>
</div>

<%= render 'form' %>

app/views/artefacts/show.html.erb
<div class="54page-header">
  <%= link_to artefacts_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_artefact_path(@artefact), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <%= link_to artefact_attachments_path(@artefact.id), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-paperclip"></span>
    Edit Attachments
  <% end %>

  <h1>Show artefact</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @artefact.name %></dd>

  <dt>Description:</dt>
  <dd><%= @artefact.description %></dd>

  <dt>Location:</dt>
  <dd><%= @artefact.location %></dd>

  <dt>Technique:</dt>
  <dd><%= @artefact.technique %></dd>
  
  <dt>Team:</dt>
  <dd><%= @artefact.team %></dd>

  <dt>Published</dt>
  <dd><%= @artefact.published %></dd>

  <% @artefact.attachments.each do |a|%>
    <dt>Attachment</dt>
    <dd><%= image_tag a.asset.url :thumb %></dd>
  <% end %>

</dl>

app/views/attachments/_form.html.erb
<%= form_for([@artefact, @attachment], :html => { :class => "form-horizontal" }) do |f| %>
  <% if @attachment.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@attachment.errors.count, "error") %> prohibited this attachment from being saved:</h4>

      <ul>
      <% @attachment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :artefact_id, :value => @artefact.id %>

  <div class="form-group">
    <%= f.label :name, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :asset, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :asset %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :weight, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :weight, :value => '0', :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/attachments/edit.html.erb
<div class="page-header">
  <%= link_to artefact_attachments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to [@artefact, @attachment], :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing attachment for <%= @artefact.name%></h1>
</div>

<%= render 'form' %>

app/views/attachments/index.html.erb
<div class="page-header">
  <%= link_to @artefact, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back to Artefact detail
  <% end %>
  <%= link_to new_artefact_attachment_path(@artefact.id), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Attachment for Artefact 
  <% end %>
  <h1>Attachments for <%= @artefact.name%></h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Asset</th>
            <th>Weight</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @attachments) do |attachment| %>
            <td><%= attachment.name %></td>
            <td><%= attachment.asset %></td>
            <td><%= attachment.weight %></td>
            <td><%= link_to 'Show', [@artefact, attachment] %></td>
        <td><%= link_to 'Edit', edit_artefact_attachment_path(@artefact, attachment) %></td>
        <td><%= link_to 'Destroy', [@artefact, attachment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/attachments/new.html.erb
<div class="page-header">
  <%= link_to artefact_attachments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New attachment for <%= @artefact.name%></h1>
</div>

<%= render 'form' %>

app/views/attachments/show.html.erb
<div class="page-header">
 
  <%= link_to artefact_attachments_path(@artefact.id), :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back to index
  <% end %>

  <%= link_to [@artefact, @attachment], :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show attachment for <%= @artefact.name%></h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @attachment.name %></dd>

  <dt>Asset:</dt>
  <dd><%= @attachment.asset %></dd>

  <dt>Weight:</dt>
  <dd><%= @attachment.weight %></dd>

</dl>

app/views/layouts/admin.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Starter Template for Bootstrap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Federico diaz admin", "#", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><%= link_to 'Artefacts', artefacts_path %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Starter Template for Bootstrap</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Project name", "#", :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable" do %>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/public.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Federico Diaz studio</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js", "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body id="public">
  <%= yield %>
</body>
</html>

app/views/library/index.html.erb
<div id='library'>
  <div id="colapse-control">
    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
      Collapsible Group Item #1
    </a>
    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
      Collapsible Group Item #2
    </a>
    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
      Collapsible Group Item #3
    </a>
  </div>
  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
      <div id="collapseOne" class="panel-collapse collapse in">
        <div class="panel-body">
          <% @artefacts.each do |artefact|%>
            <%= artefact.name%>
          <% end %>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div id="collapseTwo" class="panel-collapse collapse">
          
          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
            <% @artefact.attachments.each_with_index do |a,i|%>
              <li data-target="#carousel-example-generic" data-slide-to="<%=i%>" class="carousel-nav <%="active" if i == 0%>">
              </li>
            <%end%>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <% @artefact.attachments.each_with_index do |a,i|%>
                <div class="item <%="active" if i == 0%>">
                  <div class="static-background" style="background-image:url('<%=a.asset.url %>')">
                  Containing content
                  </div>
                </div>
              <%end%>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left"></span>
            </a>

            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
          <div>
      </div>
    </div>
    <div class="panel panel-default">
      <div id="collapseThree" class="panel-collapse collapse">
        <div class="panel-body">
          Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
        </div>
      </div>
    </div>

  </div>
</div>